export const REGISTRO_EXITOSO = "REGISTRO_EXITOSO";
export const REGISTRO_ERROR = "REGISTRO_ERROR";
export const REGISTRO_BORRAR = "REGISTRO_ERROR";
export const REGISTRO_USER = "REGISTRO_USER";
export const LOGIN_EXITOSO = "LOGIN_EXITOSO";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const CERRAR_SESION = "CERRAR_SESION";
export const RECARGAR_AUTH = "RECARGAR_AUTH";

export const MOSTRAR_ALERTA = "MOSTRAR_ALERTA";
export const OCULTAR_ALERTA = "OCULTAR_ALERTA";

export const HEADER_ACTIVO1 = "HEADER_ACTIVO1";
export const HEADER_ACTIVO2 = "HEADER_ACTIVO2";
export const HEADER_ACTIVO3 = "HEADER_ACTIVO3";
export const HEADER_ACTIVO4 = "HEADER_ACTIVO4";
export const HEADER_ACTIVO5 = "HEADER_ACTIVO5";
export const HEADER_ACTIVO6 = "HEADER_ACTIVO6";
export const HEADER_ACTIVO7 = "HEADER_ACTIVO7";

export const DETALLE_CAMISA = "DETALLE_CAMISA";
export const MODIFICAR_CAMISA = "MODIFICAR_CAMISA";
export const INCREMENTAR_CAMISA = "INCREMENTAR_CAMISA";
export const DECREMENTAR_CAMISA = "DECREMENTAR_CAMISA";
export const VARIACION_CAMISA = "VARIACION_CAMISA";
export const VACIAR_CAMISA = "VACIAR_CAMISA";

export const AÑADIR_CARRITO = "AÑADIR_CARRITO";
export const RECARGAR_CARRITO = "RECARGAR_CARRITO";
export const ELIMINAR_CARRITO = "ELIMINAR_CARRITO";
